name: Android CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Debug - List files in build directory
      run: |
        echo "Contents of app/build/outputs/apk/debug:"
        ls -R app/build/outputs/apk/debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
    
    - name: Verify artifact upload
      run: |
        echo "Artifact upload step completed"
        echo "If you see this message, it means the upload step didn't throw an error"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download APK
      uses: actions/download-artifact@v2
      with:
        name: app-debug
    
    - name: Display structure of downloaded files
      run: ls -R
      
    - name: Check APK file
      run: |
        if [ -f "app-debug.apk" ]; then
          echo "APK file exists"
          echo "File size: $(du -h app-debug.apk | cut -f1)"
        else
          echo "APK file not found"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi
