name: Android CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v2.1.4
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
        
  distribute:
    
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - name: Download APK
      uses: actions/download-artifact@v2.0.5
      id: download
      with:
        name: app
        path: ./
    # - name: upload artefact to App Center
    #   uses: wzieba/AppCenter-Github-Action@v1
    #   with:
    #     appName: InvestmentOrg/MyInvestment
    #     token: ${{secrets.APP_CENTER_TOKEN}}
    #     group: Beta Testers
    #     file: ${{steps.download.outputs.download-path}}/app-debug.apk
    #     notifyTesters: true
    #     debug: false

    - name: Login to App Center
      run: npx appcenter-cli login --token ${{secrets.APP_CENTER_TOKEN}}
    - name: Install and login to App Center
      run: |
        npm install -g appcenter-cli
        appcenter login --token "${{ secrets.APP_CENTER_TOKEN }}"
        
    - name: Distribute to App Center
      run: |
        npx appcenter-cli distribute release \
          --app InvestmentOrg/MyInvestment \
          --file ${{steps.download.outputs.download-path}}/app-debug.apk \
          --group "Beta Testers" \
          --notify-testers
