name: Android CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error

  distribute:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-debug-apk
      - name: Display structure of downloaded files
        run: ls -R
      - name: Decode Google Cloud credentials
        run: echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" | base64 -d > google-credentials.json
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
      - name: Upload APK to Google Drive
        run: |
          gcloud auth activate-service-account --key-file=google-credentials.json
          gcloud config set project ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          FILE_NAME="app-debug-${{ github.sha }}.apk"
          gcloud alpha storage cp app-debug.apk gs://your-bucket-name/${FILE_NAME}
          echo "APK uploaded to Google Cloud Storage"
      - name: Create public URL
        run: |
          FILE_NAME="app-debug-${{ github.sha }}.apk"
          gsutil acl ch -u AllUsers:R gs://your-bucket-name/${FILE_NAME}
          echo "Public URL: https://storage.googleapis.com/your-bucket-name/${FILE_NAME}"
