name: Android CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error

  distribute:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-debug-apk
      - name: Display structure of downloaded files
        run: ls -R
      - name: Setup Google Cloud credentials
        run: |
          echo '${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}' > google-credentials.json
          echo "Credentials file created"
          cat google-credentials.json
      - name: Activate service account
        run: |
          gcloud auth activate-service-account --key-file=google-credentials.json
      - name: Upload APK to Google Drive
        run: |
          FILE_NAME="app-debug-${{ github.sha }}.apk"
          gcloud drive files upload app-debug.apk --parent ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }} --name "${FILE_NAME}"
          echo "APK uploaded to Google Drive"
